### ISSUE TITLE
load() doesn't work on 2018 round 20, the 2018 Brazilian GP.

### ISSUE THREAD

**Issue by doyle524** [theOehrly/Fast-F1#156]
### Describe the issue:

Loading the 2018 Brazilian Grand Prix race session fails, with or without cache enabled, whether using get_race() or get_session(2018, 20, 'R'). It is the only GP within the scope of fast-F1 (2018-2022) that fails to load - that goes for quali, sprint, or race session.

### Reproduce the code example:

```python
import fastf1

brazil = fastf1.get_event(2018, 20)
brazilRace = brazil.get_race()
brazilRace.load()

#Alternative method that also throws the same error

#brazil = fastf1.get_session(2018, 20, 'R')
#brazil.load()
```

### Error message:

```shell
core           INFO 	Loading data for Brazilian Grand Prix - Race [v2.2.3]
api            INFO 	Fetching driver list...
Traceback (most recent call last):
  File "C:\Users\doyle\Documents\F1Project\brazil18.py", line 5, in <module>
    brazilRace.load()
  File "C:\Users\doyle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastf1\core.py", line 1055, in load
    self._load_drivers_results(livedata=livedata)
  File "C:\Users\doyle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastf1\core.py", line 1377, in _load_drivers_results
    r = self._drivers_results_from_ergast(load_results=True)
  File "C:\Users\doyle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastf1\core.py", line 1474, in _drivers_results_from_ergast
    dt = to_timedelta(ts)
  File "C:\Users\doyle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastf1\utils.py", line 142, in to_timedelta
    seconds=int(seconds), microseconds=int(msus))
ValueError: invalid literal for int() with base 10: '469s00'
```

**Comment by theOehrly** [comment]
It looks like a problem with the Ergast database from where the data is pulled. Some timestamps are formatted differently for this one race. This unexpected format causes the crash. I've contacted the admin of Ergast and suggested correcting these timestamps instead of working around this in FastF1.

**Comment by theOehrly** [comment]
Timestamp format has been corrected in Ergast and data can now be loaded for this race.
