### ISSUE TITLE
[BUG] Presence of 'index' column in pos_data causes error when merging with car_data

### ISSUE THREAD

**Issue by bruzie** [theOehrly/Fast-F1#180]
### Describe the issue:

For FP1 for the 2022 Spanish Grand Prix, the position data for the test drivers (KUB, DEV, and VIP) has an extra 'index' column:

```
     index                    Date   Status       X       Y       Z Source                   Time            SessionTime
0     1749 2022-05-20 12:30:46.133  OnTrack   750.0  -588.0  1707.0    pos 0 days 00:00:00.121000 0 days 00:45:46.122000
1     1750 2022-05-20 12:30:46.293  OnTrack   681.0  -695.0  1707.0    pos 0 days 00:00:00.281000 0 days 00:45:46.282000
2     1751 2022-05-20 12:30:46.573  OnTrack   561.0  -885.0  1708.0    pos 0 days 00:00:00.561000 0 days 00:45:46.562000
3     1752 2022-05-20 12:30:46.793  OnTrack   413.0 -1118.0  1708.0    pos 0 days 00:00:00.781000 0 days 00:45:46.782000
4     1753 2022-05-20 12:30:47.294  OnTrack   242.0 -1388.0  1708.0    pos 0 days 00:00:01.282000 0 days 00:45:47.283000
..     ...                     ...      ...     ...     ...     ...    ...                    ...                    ...
307   2056 2022-05-20 12:32:07.994  OnTrack  1189.0    95.0  1710.0    pos 0 days 00:01:21.982000 0 days 00:47:07.983000
308   2057 2022-05-20 12:32:08.254  OnTrack  1080.0   -72.0  1708.0    pos 0 days 00:01:22.242000 0 days 00:47:08.243000
309   2058 2022-05-20 12:32:08.274  OnTrack  1072.0   -85.0  1708.0    pos 0 days 00:01:22.262000 0 days 00:47:08.263000
310   2059 2022-05-20 12:32:08.634  OnTrack   929.0  -307.0  1707.0    pos 0 days 00:01:22.622000 0 days 00:47:08.623000
311   2060 2022-05-20 12:32:08.874  OnTrack   828.0  -465.0  1707.0    pos 0 days 00:01:22.862000 0 days 00:47:08.863000
```

This causes an error when attempting to merge the car and position dataframes due to this line @core.py 443::

` merged = merged.reset_index().rename(columns={'index': 'Date'})  # make 'Date' a column again`

The result is two 'Date' columns in the merged dataframe. At the end of the merge where the column types are reset, the error is thrown because the 'index' column in dtype_map is no longer present.

### Reproduce the code example:

```python
sess = fastf1.get_session(2022,'spain','fp1')
laps = sess.load()
lapd = sess.laps.pick_driver('45')
flap = lapd.pick_fastest()
pd = flap.get_pos_data()
cd = flap.get_car_data()
tele = pd.merge_channels(cd)
```

### Error message:

```shell
core           INFO     Loading data for Spanish Grand Prix - Practice 1 [v2.2.5]
api            INFO     Fetching driver list...
core        WARNING     Failed to load data from Ergast API! (This is expected for recent sessions)
api            INFO     Fetching timing data...
api            INFO     Parsing timing data...
api            INFO     Fetching timing app data...
core           INFO     Processing timing data...
api            INFO     Fetching session status data...
api            INFO     Fetching track status data...
api            INFO     Fetching car data...
api            INFO     Parsing car data...
api            INFO     Fetching position data...
api            INFO     Parsing position data...
api         WARNING     Driver 11: Position data is incomplete!
api         WARNING     Driver 23: Position data is incomplete!
api         WARNING     Driver 24: Position data is incomplete!
api         WARNING     Driver 36: Position data is incomplete!
api         WARNING     Driver 45: Position data is incomplete!
api         WARNING     Driver 88: Position data is incomplete!
api            INFO     Fetching weather data...
api            INFO     Fetching race control messages...
core           INFO     Finished loading data for 20 drivers: ['1', '63', '55', '47', '45', '44', '36', '31', '22', '20', '18', '16', '14', '10', '6', '5', '4', '3', '77', '88']

Traceback (most recent call last):
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 103, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine._get_loc_duplicates
  File "pandas/_libs/index.pyx", line 143, in pandas._libs.index.IndexEngine._maybe_get_bool_indexer
  File "pandas/_libs/index.pyx", line 161, in pandas._libs.index.IndexEngine._unpack_bool_indexer
KeyError: 'index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruzie/.local/lib/python3.8/site-packages/fastf1-2.2.5-py3.8.egg/fastf1/core.py", line 485, in merge_channels
    merged.loc[:, col] = merged.loc[:, col].astype(dtype_map[col])
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3761, in xs
    return self[key]
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/bruzie/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'index'
```

**Comment by theOehrly** [comment]
This was not limited to the three test drivers. The problem was that the position data is incomplete and did not cover the whole session. The api parser accidentally introduced the index column when extending the data with empty values.
