### ISSUE TITLE
[BUG] Loading 2021 First Circuit Error

### ISSUE THREAD

**Issue by Developer310301** [theOehrly/Fast-F1#209]
### Describe the issue:

When i try to load the Sakhir circuit on session FP1 of the year 2021 I get the current error

### Reproduce the code example:

```python
class F1tel:

    def __init__(self, season: int=get_current_season(), circuit: str=1, session: str="FP1", disable_cache: bool=False):
        if season is None or circuit is None or session is None:
            raise ValueError("season, circuit and session must be set")
        self.season = season
        self.circuit = circuit
        self.session = session
        self.disable_cache = disable_cache

        if not self.disable_cache:
            fastf1.Cache.enable_cache(get_cache_path())
        else:
            fastf1.Cache.disable()

        try:
            print("[-] Loading F1 session")
            print("[-] Season: {}".format(self.season))
            print("[-] Circuit: {}".format(self.circuit))
            print("[-] Session: {}".format(self.session))
            self.f1 = fastf1.get_session(season, circuit, session)
            self.f1.load()
            self.laps = self.f1.laps
        except Exception as e:
            print("[!] Exception: {}".format(traceback.format_exc()))
            raise e
```

### Error message:

```shell
[-] Loading F1 session
[-] Season: 2021
[-] Circuit: Sakhir
[-] Session: FP1
core           INFO     Loading data for Bahrain Grand Prix - Practice 1 [v2.2.9]
api            INFO     Using cached data for driver_info
[!] Exception: Traceback (most recent call last):
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/f1tel_gui/F1tel.py", line 28, in __init__
    self.f1 = fastf1.get_session(season, circuit, session)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/fastf1/events.py", line 272, in get_session
    event = get_event(year, gp, force_ergast=force_ergast)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/fastf1/events.py", line 329, in get_event
    event = schedule.get_event_by_name(gp)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/fastf1/events.py", line 615, in get_event_by_name
    return self.loc[index]
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 3864, in xs
    loc = index.get_loc(key)
  File "/home/federico/Documenti/GitHub/F1-Telemetry-GUI/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

**Comment by theOehrly** [comment]
Judging by the type hints in your init signature and by the default value (although they don't match), I suspect that you are passing the event *number* (your 'circuit' arg) as a *string* to `get_session`. FastF1 then tries and fails to find corresponding event by name.
You must pass the number as integer.

See the docs:
"gp (number or string) –

Name as str or round number as int. If gp is a string, a fuzzy match will be performed on all events and the closest match will be selected. Fuzzy matching uses country, location, name and officialName of each event as reference."
