### ISSUE TITLE
[BUG] Error loading quali session of 2022 races after Azerbaijan GP

### ISSUE THREAD

**Issue by AdmiralBulldog** [theOehrly/Fast-F1#235]
### Describe the issue:

Can't load quali session from Azerbaijan GP 2022 or any event after that in 2022. It produces a warning first when using `get_event()` and error later when using `session.load()`

### Reproduce the code example:

```python
event = fastf1.get_event(2022, 'FORMULA 1 AZERBAIJAN GRAND PRIX 2022')
quali = event.get_session('Q')
quali.load()
```

### Error message:

```shell
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v2.2.9]
api            INFO 	Using cached data for driver_info
session     WARNING 	Request for URL http://ergast.com/api/f1/2022/8/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/opt/software/lib/python3.9/site-packages/requests_cache/session.py", line 230, in _resend_and_ignore
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/opt/software/lib/python3.9/site-packages/requests_cache/session.py", line 193, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "/opt/software/lib/python3.9/site-packages/requests_cache/backends/base.py", line 97, in save_response
    self.responses[cache_key] = cached_response
  File "/opt/software/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 268, in __setitem__
    super().__setitem__(key, serialized_value)
  File "/opt/software/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 220, in __setitem__
    con.execute(
sqlite3.OperationalError: attempt to write a readonly database
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Input In [95], in <cell line: 1>()
----> 1 quali.load()

File /opt/software/lib/python3.9/site-packages/fastf1/core.py:1082, in Session.load(self, laps, telemetry, weather, messages, livedata)
   1079 if self.f1_api_support:
   1080     if laps:
   1081         # try:
-> 1082         self._load_laps_data(livedata)
   1083         # except Exception as exc:
   1084         #     logging.warning("Failed to load lap data!")
   1085         #     logging.debug("Lap data failure traceback:", exc_info=exc)
   1087     if telemetry:

File /opt/software/lib/python3.9/site-packages/fastf1/core.py:1145, in Session._load_laps_data(self, livedata)
   1144 def _load_laps_data(self, livedata):
-> 1145     data, _ = api.timing_data(self.api_path, livedata=livedata)
   1146     app_data = api.timing_app_data(self.api_path, livedata=livedata)
   1147     logging.info("Processing timing data...")

File /opt/software/lib/python3.9/site-packages/fastf1/api.py:265, in Cache.api_request_wrapper.<locals>._cached_api_request(api_path, response, livedata)
    262 else:  # cached data does not yet exist for this api request
    263     logging.info(f"No cached data found for {func_name}. "
    264                  f"Loading data...")
--> 265     data = func(
    266         api_path, response=response, livedata=livedata
    267     )
    268     if data is not None:
    269         cls._write_cache(data, cache_file_path)

File /opt/software/lib/python3.9/site-packages/fastf1/api.py:491, in timing_data(path, response, livedata)
    489 elif response is None:  # no previous response provided
    490     logging.info("Fetching timing data...")
--> 491     response = fetch_page(path, 'timing_data')
    492     if response is None:  # no response received
    493         raise SessionNotAvailableError(
    494             "No data for this session! If this session only finished "
    495             "recently, please try again in a few minutes."
    496         )

File /opt/software/lib/python3.9/site-packages/fastf1/api.py:1560, in fetch_page(path, name)
   1558 is_stream = 'jsonStream' in page
   1559 is_z = '.z.' in page
-> 1560 r = Cache.requests_get(base_url + path + pages[name], headers=headers)
   1561 if r.status_code == 200:
   1562     raw = r.content.decode('utf-8-sig')

File /opt/software/lib/python3.9/site-packages/fastf1/api.py:161, in Cache.requests_get(cls, *args, **kwargs)
    159 if (cls._requests_session is None) or cls._tmp_disabled:
    160     return requests.get(*args, **kwargs)
--> 161 return cls._requests_session.get(*args, **kwargs)

File /opt/software/lib/python3.9/site-packages/requests/sessions.py:555, in Session.get(self, url, **kwargs)
    547 r"""Sends a GET request. Returns :class:`Response` object.
    548 
    549 :param url: URL for the new :class:`Request` object.
    550 :param \*\*kwargs: Optional arguments that ``request`` takes.
    551 :rtype: requests.Response
    552 """
    554 kwargs.setdefault('allow_redirects', True)
--> 555 return self.request('GET', url, **kwargs)

File /opt/software/lib/python3.9/site-packages/requests_cache/session.py:115, in CacheMixin.request(self, method, url, expire_after, *args, **kwargs)
    112     kwargs['headers']['Cache-Control'] = f'max-age={get_expiration_seconds(expire_after)}'
    114 with patch_form_boundary(**kwargs):
--> 115     return super().request(method, url, *args, **kwargs)

File /opt/software/lib/python3.9/site-packages/requests/sessions.py:542, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    537 send_kwargs = {
    538     'timeout': timeout,
    539     'allow_redirects': allow_redirects,
    540 }
    541 send_kwargs.update(settings)
--> 542 resp = self.send(prep, **send_kwargs)
    544 return resp

File /opt/software/lib/python3.9/site-packages/requests_cache/session.py:147, in CacheMixin.send(self, request, expire_after, **kwargs)
    145 # If the response is expired or missing, or the cache is disabled, then fetch a new response
    146 if cached_response is None:
--> 147     response = self._send_and_cache(request, actions, **kwargs)
    148 elif is_expired and self.stale_if_error:
    149     response = self._resend_and_ignore(request, actions, cached_response, **kwargs)

File /opt/software/lib/python3.9/site-packages/requests_cache/session.py:193, in CacheMixin._send_and_cache(self, request, actions, cached_response, **kwargs)
    190 actions.update_from_response(response)
    192 if self._is_cacheable(response, actions):
--> 193     self.cache.save_response(response, actions.cache_key, actions.expires)
    194 elif cached_response and response.status_code == 304:
    195     return self._update_revalidated_response(actions, response, cached_response)

File /opt/software/lib/python3.9/site-packages/requests_cache/backends/base.py:97, in BaseCache.save_response(self, response, cache_key, expires)
     95 cached_response = CachedResponse.from_response(response, expires=expires)
     96 cached_response = redact_response(cached_response, self.ignored_parameters)
---> 97 self.responses[cache_key] = cached_response
     98 for r in response.history:
     99     self.redirects[self.create_key(r.request)] = cache_key

File /opt/software/lib/python3.9/site-packages/requests_cache/backends/sqlite.py:268, in SQLitePickleDict.__setitem__(self, key, value)
    266 if isinstance(serialized_value, bytes):
    267     serialized_value = sqlite3.Binary(serialized_value)
--> 268 super().__setitem__(key, serialized_value)

File /opt/software/lib/python3.9/site-packages/requests_cache/backends/sqlite.py:220, in SQLiteDict.__setitem__(self, key, value)
    218 def __setitem__(self, key, value):
    219     with self.connection(commit=True) as con:
--> 220         con.execute(
    221             f'INSERT OR REPLACE INTO {self.table_name} (key,value) VALUES (?,?)',
    222             (key, value),
    223         )

OperationalError: attempt to write a readonly database
```

**Comment by theOehrly** [comment]
I'm failing to reproduce this problem. Also, it doesn't look like this problem is really caused by FastF1. If the problem still exists, please try clearing the cache of FastF1. If that does not solve the problem, please provide a full minimal example. Your example above does not include all the code that is necessary to run the script and reproduce the problem.

**Comment by oscr** [comment]
I also failed to reproduce this problem.

Maybe it's related to filesystem privileges? Something similar to: https://stackoverflow.com/questions/40703228/python-sqlite3-operationalerror-attempt-to-write-a-readonly-database 

Is this on macOS?

**Comment by AdmiralBulldog** [comment]
Thanks for replying, indeed clearing the cache seems to have fixed the problem. I'm pretty sure I tried that before but I think I deleted the cache just for that event, not the whole folder. I'm actually running this notebook in my Uni's server which is running Ubuntu, since I don't always have access to my computer with python 3.9.

**Comment by oscr** [comment]
Great to hear @AdmiralBulldog! Good luck with future fastf1 hacking!
