### ISSUE TITLE
[BUG] Load sprint session

### ISSUE THREAD

**Issue by tarik-boumaza** [theOehrly/Fast-F1#274]
### Describe the issue:

I tied to import sprint sessions of many events and I always get the same error message.

(fastf1 Version: 2.2.0a0)

### Reproduce the code example:

```python
import fastf1
fastf1.Cache.enable_cache('./cache')
session = fastf1.get_session(2022, 4, 4)
```

### Error message:

```shell
Traceback (most recent call last):
  File "website/sprint.py", line 3, in <module>
    session = fastf1.get_session(2022, 4, 4)
  File "/home/tarik/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/events.py", line 270, in get_session
    return event.get_session(identifier)
  File "/home/tarik/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/events.py", line 777, in get_session
    return Session(event=self, session_name=session_name)
  File "/home/tarik/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/core.py", line 874, in __init__
    self.date = self.event.get_session_date(session_name)
  File "/home/tarik/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/events.py", line 735, in get_session_date
    session_name = self.get_session_name(identifier)
  File "/home/tarik/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/events.py", line 704, in get_session_name
    raise ValueError(f"Invalid session type '{identifier}'")
ValueError: Invalid session type 'Sprint'
```

**Comment by theOehrly** [comment]
Please update to the latest version of FastF1. 
Sprint sessions in 2022 are not supported yet in version 2.2.0.
(See #160 for reference)
