### ISSUE TITLE
Telemetry does not contain required channels 'Time' and 'Speed'  for Azerbaijan Grand Prix - Qualifying

### ISSUE THREAD

**Issue by Xwang1976** [theOehrly/Fast-F1#29]
I get the following error when trying to compare best Q laps of LEC and HAM. Other sessions work correctly:

core        WARNING 	Ergast API lookup failed. The session is very recent and not yet available or does not exist.
core           INFO 	Loading laps for Azerbaijan Grand Prix - Qualifying [v2.1.5]
api            INFO 	Using cached data for timing_data
api            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
api            INFO 	Using cached data for session_status_data
api            INFO 	Using cached data for track_status_data
api            INFO 	Using cached data for car_data
api            INFO 	Using cached data for position_data
core           INFO 	Loaded data for 20 drivers: ['77', '31', '10', '4', '9', '63', '99', '6', '33', '44', '7', '47', '3', '55', '22', '14', '16', '5', '18', '11']
Traceback (most recent call last):

  File "/home/andreak/src/Python/F1data/F1data_compare2pilots_speeds_bestLap.py", line 25, in <module>
    ax.plot(lec.telemetry['Distance'], lec.telemetry['Speed'],

  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1772, in telemetry
    return self.get_telemetry()

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1793, in get_telemetry
    car_data = car_data.add_distance().add_relative_distance().add_driver_ahead()

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 797, in add_driver_ahead
    drv_ahead, dist = self.calculate_driver_ahead()

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 889, in calculate_driver_ahead
    drv_tel = self.session.car_data[drv].slice_by_lap(relevant_laps).add_distance() \

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 735, in add_distance
    return self.join(pd.DataFrame({'Distance': self.integrate_distance()}), how='outer')

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 827, in integrate_distance
    ds = self.calculate_differential_distance()

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 809, in calculate_differential_distance
    raise ValueError("Telemetry does not contain required channels 'Time' and 'Speed'.")

ValueError: Telemetry does not contain required channels 'Time' and 'Speed'.

**Comment by theOehrly** [comment]
This is a slightly weird bug caused by a combination of things.

You are accessing the `lap.telemetry` property to get the car's speed and distance. `lap.telemetry` in the background merges car data and position data  and adds all computed data channels (like 'Distance' for example). The problem is, that it also adds 'DistanceToDriverAhead'. To calculate this, telemetry of all drivers needs to be evaluated. Stroll crashing on his first and only lap causes some bug here.

To get the data you want, you should do the following:

```
lec_tel = lec.get_car_data()
lec_tel = lec_tel.add_distance()

ax.plot(lec_tel['Distance'], lec_tel['Speed'])
```
(I'm guessing that's about what you want to do?)

You should use this method all the time anyways because it will give you more accurate data. The merging of car data and position data done in `.telemetry` requires interpolation which reduces the accuracy slightly. If you don't want to use the position data (x,y coordinates of the car on track), you should just use `.get_car_data()`

I'll look into fixing this properly, but it probably won't be soon.

**Comment by Xwang1976** [comment]
I've done as you suggested and it works perfectly.Thanks!!!

**Comment by ProjectF1** [comment]
Hi there. I'm doing some work that requires the [X, Y] coordinates of the position channel alongside the telemetry data from the car channel. Normally I just use the .get.telemetry() function because it is merged already however it is throwing up an error for the Azerbaijan GP (as discussed here already). Is there a workaround I can use or will I need to wait for you to do the fixes you mentioned? Thanks in advance for your time to respond and thank you in general for your work on this package.
