### ISSUE TITLE
get_car_data() / get_telemetry errors

### ISSUE THREAD

**Issue by JSEHV** [theOehrly/Fast-F1#32]
Having an issue pulling the car data:

```
race = ff1.get_session(2021, 9, 'R')
laps = race.load_laps()
ver = laps.pick_driver('VER').pick_fastest()
ver_car = ver.get_car_data()
```
As result I get the output below
```
Traceback (most recent call last):
  File "graphing.py", line 29, in <module>
    ver_car = ver.get_car_data()
  File "/Users/.../Library/Python/3.8/lib/python/site-packages/fastf1/core.py", line 1919, in get_car_data
    car_data = self.session.car_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)
KeyError: '33'
```
Same when trying to get telemetry data instead of only car data:
```
race = ff1.get_session(2021, 9, 'R')
laps = race.load_laps()
ver = laps.pick_driver('VER').pick_fastest()
ver_car = ver.get_telemetry()
```
As result I get the output below
```
Traceback (most recent call last):
  File "graphing.py", line 29, in <module>
    ver_car = ver.get_telemetry()
  File "/Users/.../Library/Python/3.8/lib/python/site-packages/fastf1/core.py", line 1891, in get_telemetry
    pos_data = self.get_pos_data(pad=1, pad_side='both')
  File "/Users/.../Library/Python/3.8/lib/python/site-packages/fastf1/core.py", line 1933, in get_pos_data
    pos_data = self.session.pos_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)
KeyError: '33'
```

Is this also related to the DriverNumber != drv_num issue?

**Comment by JSEHV** [comment]
Forgot `with_telemetry=True` in `load_laps()`

Solved.
