### ISSUE TITLE
Example throws KeyError

### ISSUE THREAD

**Issue by ahalekelly** [theOehrly/Fast-F1#33]
Hey I'm getting the following error from the example code in the Readme. Any idea what's going on?
```
core           INFO     Loading laps for Turkish Grand Prix - Race [v2.1.6]
api            INFO     Using cached data for timing_data
api            INFO     Using cached data for timing_app_data
core           INFO     Processing timing data...
api            INFO     Using cached data for session_status_data
api            INFO     Using cached data for track_status_data
api            INFO     Using cached data for weather_data
core           INFO     Loaded data for 20 drivers: ['18', '33', '11', '23', '3', '44', '31', '7', '77', '99', '5', '16', '20', '4', '55', '26', '8', '6', '10', '63']
Traceback (most recent call last):
  File "c:\Users\ahale\Documents\lec-ham-ex.py", line 15, in <module>
    ax.plot(lec['LapNumber'], lec['LapTime'], color='red')
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\axes\_axes.py", line 1646, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\axes\_base.py", line 216, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\axes\_base.py", line 337, in _plot_args
    self.axes.xaxis.update_units(x)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\axis.py", line 1510, in update_units
    converter = munits.registry.get_converter(data)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timple\patches.py", line 115, in get_converter
    if np.iterable(x) and hasattr(x[0], 'value'):
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\indexes\base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas\_libs\index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1005, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
```

**Comment by ahalekelly** [comment]
Huh The Leclerc example throws a different error:

```
Pronto Sebastian?
core           INFO     Loading laps for Italian Grand Prix - Qualifying [v2.1.6]
api            INFO     No cached data found for timing_data. Loading data...
api            INFO     Fetching timing data...
api            INFO     Parsing timing data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for timing_app_data. Loading data...
api            INFO     Fetching timing app data...
api            INFO     Data has been written to cache!
core           INFO     Processing timing data...
api            INFO     No cached data found for session_status_data. Loading data...
api            INFO     Fetching session status data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for track_status_data. Loading data...
api            INFO     Fetching track status data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for car_data. Loading data...
api            INFO     Fetching car data...
api            INFO     Parsing car data...
api            INFO     Data has been written to cache!
api            INFO     No cached data found for position_data. Loading data...
api            INFO     Fetching position data...
api            INFO     Parsing position data...
api            INFO     Data has been written to cache!
Traceback (most recent call last):
  File "c:\Users\ahale\Documents\ff1-lec.py", line 17, in <module>
    laps = monza_quali.load_laps(with_telemetry=True)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fastf1\core.py", line 1253, in load_laps
    self.load_telemetry(livedata=livedata)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fastf1\core.py", line 1356, in load_telemetry
    drv_car['Date'] = drv_car['Date'].round('ms')
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\series.py", line 2145, in round
    result = com.values_from_object(self).round(decimals)
TypeError: an integer is required (got type str)
```

**Comment by theOehrly** [comment]
I'm pretty sure that's related to either pandas or numpy being a too old version.

Can you give me the output of calling `pip list`? That should be a list of all installed modules with version number. I need to figure out what versions start to create issues.

After that you could update numpy and pandas to see if that fixes the issue.

**Comment by ahalekelly** [comment]
Ah that makes sense. That was numpy 1.18.4 and pandas 1.0.4. Upgrading numpy to 1.21.0 did nothing, then upgrading pandas to 1.3.0 made the error change to a different one. After clearing the cache it works! Thank you.
