### ISSUE TITLE
Qualifying data unavailable during sprint race weekend

### ISSUE THREAD

**Issue by langenf1** [theOehrly/Fast-F1#35]
Hello,

I'm trying to load the data for todays qualifying and the Ergast API lookup fails (obviously not fastf1's fault). 
How will getting data for this qualifying and the sprint race qualifying work if Ergast doesn't update their API?

Thank you.

**Comment by Xwang1976** [comment]
Same problem for me.
I've saved the data from the livestreaming and I can load it (I've chosen to load them as an FP2 session).

**Comment by langenf1** [comment]
@Xwang1976 Could you share the data if it's not too much trouble?

**Comment by Xwang1976** [comment]
> @Xwang1976 Could you share the data if it's not too much trouble?

How?

**Comment by theOehrly** [comment]
I feared as much. Don't blame Ergast though ;) It is a problem with fastf1 because a hard assumption is made that qualifying takes place on a saturday.

Here's a workaround:

```
# load as fp2 and manually set the correct api path
session = ff1.get_session(2021, 'British Grand Prix', 'FP2')
session.api_path = '/static/2021/2021-07-18_British_Grand_Prix/2021-07-16_Qualifying/'

laps = session.load_laps()
```

**Comment by langenf1** [comment]
@theOehrly Thank you, this worked, any ideas on how the sprint qualy will work?

**Comment by Xwang1976** [comment]
> session.api_path = '/static/2021/2021-07-18_British_Grand_Prix/2021-07-16_Qualifying/'
> 
> laps = session.load_laps()

Thank you!
I've deleted the files from the cache which have been created from livetiming and I've done as you have suggested, but in such a way in the cache data are put in a folder named 2021-07-16_Qualifying while getting them from livetimeing they were put under 2021-07-16_Practice_2.
So when I try to create a graph it does not found neither an FP2 nor a Q valid session.

runfile('/home/andreak/src/Python/F1data/F1data_compare2pilots_speeds_bestLap.py', wdir='/home/andreak/src/Python/F1data')
core        WARNING 	Ergast API lookup failed. The session is very recent and not yet available or does not exist.
core           INFO 	Loading laps for British Grand Prix - Practice 2 [v2.1.5]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
Traceback (most recent call last):

  File "/home/andreak/src/Python/F1data/F1data_compare2pilots_speeds_bestLap.py", line 26, in <module>
    laps = data.load_laps(with_telemetry=True)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1142, in load_laps
    data, _ = api.timing_data(self.api_path, livedata=livedata)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 178, in cached_api_request
    data = func(api_path, response=response, livedata=livedata)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 296, in timing_data
    raise SessionNotAvailableError("No data for this session! Are you sure this session wasn't cancelled?")

SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?


runfile('/home/andreak/src/Python/F1data/F1data_compare2pilots_speeds_bestLap.py', wdir='/home/andreak/src/Python/F1data')
core        WARNING 	Ergast API lookup failed. The session is very recent and not yet available or does not exist.
core           INFO 	Loading laps for British Grand Prix - Qualifying [v2.1.5]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
Traceback (most recent call last):

  File "/home/andreak/src/Python/F1data/F1data_compare2pilots_speeds_bestLap.py", line 26, in <module>
    laps = data.load_laps(with_telemetry=True)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1142, in load_laps
    data, _ = api.timing_data(self.api_path, livedata=livedata)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 178, in cached_api_request
    data = func(api_path, response=response, livedata=livedata)

  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 296, in timing_data
    raise SessionNotAvailableError("No data for this session! Are you sure this session wasn't cancelled?")

SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?

**Comment by theOehrly** [comment]
You need to have this line

```session.api_path = '/static/2021/2021-07-18_British_Grand_Prix/2021-07-16_Qualifying/'```

in every single script you run. Even if you just want to load the already cached data. The internal cache is structured using the api path. So it needs to be set correctly.

(Another way would be to rename the directory inside the main cache folder to the expected path)

**Comment by Xwang1976** [comment]
> You need to have this line
> 
> `session.api_path = '/static/2021/2021-07-18_British_Grand_Prix/2021-07-16_Qualifying/'`
> 
> in every single script you run. Even if you just want to load the already cached data. The internal cache is structured using the api path. So it needs to be set correctly.
> 
> (Another way would be to rename the directory inside the main cache folder to the expected path)

Thank you.
I've used the second approach (renaming the main cache folder from 2021-07-16_Qualifying to 2021-07-16_Practice_2) and it works perfectly.

**Comment by theOehrly** [comment]
Sprint qualifying tomorrow will likely be the same problem. I guess the api path will be

```'/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Sprint_Qualifying/'```
or
```'/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Sprint/'```

but I won't know until after.

This problem also happens if a session gets moved to a different day due to difficult weather. I think there's one weekend in Suzuka a from two or three years ago where qualifying was on a sunday morning. It's the same problem. I need to make this more flexible, so it automatically works. But I'm not yet sure how I'll do it. Hopefully I'll get it done until the second sprint quali test weekend.

(And we'll leave this open for now, so it's easier to find.)

**Comment by Xwang1976** [comment]
What's the api path of this morning (staurday) practise ?

**Comment by theOehrly** [comment]
should be ```'/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Practice_2/'```

**Comment by langenf1** [comment]
'/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Sprint_Qualifying/'
Is indeed the correct path

**Comment by Xwang1976** [comment]
> should be `'/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Practice_2/'`

Thanks.
Sprint qualification is '/static/2021/2021-07-18_British_Grand_Prix/2021-07-17_Sprint_Qualifying/' (just downloaded).

IMHO in order to be able to compare data between different GPs the sprint qualifying should be managed by fastf1 with a specific session type (like SQ). For these silly weekends free practice would be FP1 and FP2, qualification would be the second Friday session and race will be race.
Are you going to do something similar?

**Comment by theOehrly** [comment]
> IMHO in order to be able to compare data between different GPs the sprint qualifying should be managed by fastf1 with a specific session type (like SQ). For these silly weekends free practice would be FP1 and FP2, qualification would be the second Friday session and race will be race.
> Are you going to do something similar?

Yes, that's most certainly what I'm going to do. Sprint qualifying needs to be a separate session type.

**Comment by theOehrly** [comment]
I have just made a new release of FastF1, as the upcoming weekend features a sprint qualifying again.

This release patches the previous sprint qualifying weekend in Silverstone and the upcoming weekend in Monza specifically. I've not managed to finish a proper implementation of an event schedule in time for this race weekend. It will be part of a larger future update though and should prevent problems like this in the future.

Here's hoping that everything works for this race weekend.

**Comment by Xwang1976** [comment]
> I have just made a new release of FastF1, as the upcoming weekend features a sprint qualifying again.
> 
> This release patches the previous sprint qualifying weekend in Silverstone and the upcoming weekend in Monza specifically. I've not managed to finish a proper implementation of an event schedule in time for this race weekend. It will be part of a larger future update though and should prevent problems like this in the future.
> 
> Here's hoping that everything works for this race weekend.

I've just updated to the latest version and I've downloaded with it all the the racing weekend data since 2018.
Then I've compared with diff the folder with the cached data (including telemetry) and the old cache folder and a lot of files are reported to be different. Why?
Secondly I see that 2021 British Gp does not have the Sprint race data. Why?

**Comment by theOehrly** [comment]
Can you elaborate this a bit more?

First, what do you mean, you don't have sprint race data? I do get data (including telemetry) for the race and sprint qualifying of the 2021 British GP.

Second, concerning the different files, the cached data contains pickled pandas DataFrames. Whenever the DataFrame object of pandas changes, which may happen when updating to newer versions of pandas, the files change too. This actually means that the cache needs to be recreated after updating pandas. Most likely this is what causes the different files.

**Comment by Xwang1976** [comment]
This is the tree of the 2021-07-18_British_Grand_Prix folder
.
├── 2021-07-16_Practice_1
│   ├── car_data.ff1pkl
│   ├── position_data.ff1pkl
│   ├── session_status_data.ff1pkl
│   ├── timing_app_data.ff1pkl
│   ├── timing_data.ff1pkl
│   ├── track_status_data.ff1pkl
│   └── weather_data.ff1pkl
├── 2021-07-16_Qualifying
│   ├── car_data.ff1pkl
│   ├── position_data.ff1pkl
│   ├── session_status_data.ff1pkl
│   ├── timing_app_data.ff1pkl
│   ├── timing_data.ff1pkl
│   ├── track_status_data.ff1pkl
│   └── weather_data.ff1pkl
├── 2021-07-17_Practice_2
│   ├── car_data.ff1pkl
│   ├── position_data.ff1pkl
│   ├── session_status_data.ff1pkl
│   ├── timing_app_data.ff1pkl
│   ├── timing_data.ff1pkl
│   ├── track_status_data.ff1pkl
│   └── weather_data.ff1pkl
└── 2021-07-18_Race
    ├── car_data.ff1pkl
    ├── position_data.ff1pkl
    ├── session_status_data.ff1pkl
    ├── timing_app_data.ff1pkl
    ├── timing_data.ff1pkl
    ├── track_status_data.ff1pkl
    └── weather_data.ff1pkl

As you can see there is no Sprint race sub folder.
This is what I get downloading the weekend:

core           INFO 	Loading laps for British Grand Prix - Practice 1 [v2.1.8]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
api            INFO 	Parsing timing data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for timing_app_data. Loading data...
api            INFO 	Fetching timing app data...
api            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
api            INFO 	No cached data found for session_status_data. Loading data...
api            INFO 	Fetching session status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for track_status_data. Loading data...
api            INFO 	Fetching track status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for car_data. Loading data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for position_data. Loading data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for weather_data. Loading data...
api            INFO 	Fetching weather data...
api            INFO 	Data has been written to cache!
core           INFO 	Loaded data for 20 drivers: ['16', '55', '33', '4', '18', '99', '3', '9', '22', '14', '44', '5', '77', '10', '47', '63', '11', '6', '7', '31']
core           INFO 	Loading laps for British Grand Prix - Practice 2 [v2.1.8]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
api            INFO 	Parsing timing data...
api         WARNING 	Driver 55: Ignoring late data for a previously processed lap.The data may contain errors (previous: 21; current 22)
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for timing_app_data. Loading data...
api            INFO 	Fetching timing app data...
api            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
api            INFO 	No cached data found for session_status_data. Loading data...
api            INFO 	Fetching session status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for track_status_data. Loading data...
api            INFO 	Fetching track status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for car_data. Loading data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for position_data. Loading data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for weather_data. Loading data...
api            INFO 	Fetching weather data...
api            INFO 	Data has been written to cache!
core           INFO 	Loaded data for 20 drivers: ['16', '55', '33', '4', '18', '99', '3', '9', '22', '14', '44', '5', '77', '10', '47', '63', '11', '6', '7', '31']
core           INFO 	Loading laps for British Grand Prix - Qualifying [v2.1.8]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
*********************************************************************
Error downloading FP3 of gp=2021\10
Traceback (most recent call last):
  File "/home/andreak/src/Python/F1data/getDataFromF1.py", line 68, in <module>
    ff1.get_session(year,gp).get_practice(3).load_laps(with_telemetry=True)
  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 995, in get_practice
    return Session(self, f'Practice {number}')
  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1050, in __init__
    self.date = self._get_session_date()
  File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1130, in _get_session_date
    date = SPRINT_QUALIFYING_LOOKUP[self.weekend.gp][self.name]
KeyError: 'Practice 3'

*********************************************************************
api            INFO 	Parsing timing data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for timing_app_data. Loading data...
api            INFO 	Fetching timing app data...
api            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
api            INFO 	No cached data found for session_status_data. Loading data...
api            INFO 	Fetching session status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for track_status_data. Loading data...
api            INFO 	Fetching track status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for car_data. Loading data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for position_data. Loading data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for weather_data. Loading data...
api            INFO 	Fetching weather data...
api            INFO 	Data has been written to cache!
core           INFO 	Loaded data for 20 drivers: ['16', '55', '33', '4', '18', '99', '3', '9', '22', '14', '44', '5', '77', '10', '47', '63', '11', '6', '7', '31']
core           INFO 	Loading laps for British Grand Prix - Race [v2.1.8]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
api            INFO 	Parsing timing data...
api         WARNING 	Driver  4: Ignoring late data for a previously processed lap.The data may contain errors (previous: 43; current 44)
api         WARNING 	Driver 55: Ignoring late data for a previously processed lap.The data may contain errors (previous: 7; current 8)
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for timing_app_data. Loading data...
api            INFO 	Fetching timing app data...
api            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
api            INFO 	No cached data found for session_status_data. Loading data...
api            INFO 	Fetching session status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for track_status_data. Loading data...
api            INFO 	Fetching track status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for car_data. Loading data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for position_data. Loading data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api         WARNING 	Driver 241: Position data is incomplete!
api         WARNING 	Driver 242: Position data is incomplete!
api         WARNING 	Driver 243: Position data is incomplete!
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for weather_data. Loading data...
api            INFO 	Fetching weather data...
api            INFO 	Data has been written to cache!
core           INFO 	Loaded data for 19 drivers: ['16', '55', '4', '18', '99', '3', '9', '22', '14', '44', '5', '77', '10', '47', '63', '11', '6', '7', '31']
Finished  gp=2021\10

**Comment by theOehrly** [comment]
Did you use event='SQ' to load it? That's the abbreviation I chose for it. 
I've updated the docs, but I know, it's a well hidden small change...
But it's the only and best thing I could do quickly

**Comment by Xwang1976** [comment]
> Did you use event='SQ' to load it? That's the abbreviation I chose for it.
> I've updated the docs, but I know, it's a well hidden small change...
> But it's the only and best thing I could do quickly

No, I didn't.
It works as expected.
Sorry and thank you!

**Comment by theOehrly** [comment]
Ok, that's great. I feared it's an easy to miss change.

**Comment by zyxwl2015** [comment]
What's the api path for this Friday's qualifying? I've tried session.api_path = '/static/2021/2021-09-10_Italian_Grand_Prix/2021-09-10_Qualifying/' and it's not working

**Comment by theOehrly** [comment]
You don't need to set the api path manually anymore with the latest update as described above.

Just use ``session = get_session(2021, "Monza", 'Q')`` as you normally would.
