### ISSUE TITLE
Issues with qualifying of Monza

### ISSUE THREAD

**Issue by Matteo998** [theOehrly/Fast-F1#42]
This is what I get when I execute the code: 

```
core        WARNING     Ergast API lookup failed. The session is very recent and not yet available or does not exist.
core           INFO     Loading laps for Italian Grand Prix - Qualifying [v2.1.6]
api            INFO     No cached data found for timing_data. Loading data...
api            INFO     Fetching timing data...
Traceback (most recent call last):
  File "plot_qualifying_results.py", line 25, in <module>
    laps = quali.load_laps()
  File "C:\Users\matte\Desktop\Fast-F1-master\fastf1\core.py", line 1148, in load_laps
    data, _ = api.timing_data(self.api_path, livedata=livedata)
  File "C:\Users\matte\Desktop\Fast-F1-master\fastf1\api.py", line 178, in cached_api_request
    data = func(api_path, response=response, livedata=livedata)
  File "C:\Users\matte\Desktop\Fast-F1-master\fastf1\api.py", line 296, in timing_data
    raise SessionNotAvailableError("No data for this session! Are you sure this session wasn't cancelled?")
fastf1.api.SessionNotAvailableError: No data for this session! Are you sure this session wasn't cancelled?
```

**Comment by theOehrly** [comment]
You need to update to the latest version (2.1.8) so that the  changed order of sessions of this sprint qualifying weekend is supported. 
You're still using v2.1.6
