### ISSUE TITLE
[BUG] Issue loading laps - Ergast Certificate Error

### ISSUE THREAD

**Issue by manpean** [theOehrly/Fast-F1#443]
### Describe the issue:

Hi,

I have seen that the version 3.1.1 is relased and i have update. However when i try to load the laps, it does not load anything. The same code worked in 3.0.7. Also I am having problms with the certificate of https://ergast.com/api/

I do not what is the reason of the error but I hope it helps.

Thanks for your effort

    
 

### Reproduce the code example:

```python
term = ff1.get_session(2023, 13, 5)
term.load()
    
drv_laps={}
    
for drv in term.drivers:
    drv_laps[drv] = term.laps.pick_driver(drv)

print(drv_laps)
```

### Error message:

```shell
Request for URL https://ergast.com/api/f1/2023/13/results.json failed; using cached response
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files\Spyder\pkgs\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Spyder\pkgs\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Program Files\Spyder\pkgs\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files\Spyder\pkgs\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Program Files\Spyder\pkgs\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)


{}
```

**Comment by theOehrly** [comment]
This is not an issue with FastF1. The SSL Certificate for ergast.com expired this morning (29.08.2023). Coincidentally, I release the new version around the same time.

The proper solution is to wait until the administrator for Ergast renews the certificate. The problem has already been reported.

A temporary workaround would be to add 
```
fastf1.ergast.interface.BASE_URL = 'http://ergast.com/api/f1'
```
to the beginning of any script you run. FastF1 will then use HTTP instead of HTTPS for every request to Ergast.

**Comment by manpean** [comment]
Thanks!!

**Comment by theOehrly** [comment]
The certificate has been renewed. Everything is working again.
