### ISSUE TITLE
Issue with live timing

### ISSUE THREAD

**Issue by bpitarch** [theOehrly/Fast-F1#59]
Hi,

I've tried to get the live timing data for the FP1 Qatar using the command that is in the documentation but I'm receiving an error.

The command I'm using
`python -m fastf1.livetiming save qatar_fp1_data.txt`

The full error I'm getting
`Traceback (most recent call last):
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\livetiming\__main__.py", line 60, in <module>
    args.func(args)  # call function associated with subparser
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\livetiming\__main__.py", line 10, in save
    client.start()
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\livetiming\client.py", line 185, in start
    asyncio.run(self._async_start())
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\livetiming\client.py", line 177, in _async_start
    await asyncio.gather(asyncio.ensure_future(self._supervise()),
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\livetiming\client.py", line 141, in _run
    self._connection = Connection(self._connection_url, session=session)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\signalr_aio\_connection.py", line 24, in __init__
    self.__transport = Transport(self)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\signalr_aio\transports\_transport.py", line 34, in __init__
    self._set_loop()
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\site-packages\signalr_aio\transports\_transport.py", line 42, in _set_loop
    self.invoke_queue = asyncio.Queue(loop=self.ws_loop)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py", line 33, in __init__
    super().__init__(loop=loop)
  File "C:\Users\milen\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary`

I'm using the version 2.1.11 of the fastf1 package and the 3.10.0 python version.

**Comment by theOehrly** [comment]
Looks like the module that is used for connecting to the data stream (signalr-client-aio) is not compatible with python 3.10.
The only way to solve this for now is to use python 3.8 or 3.9.
There's no easy way for me to fix this as the issue is not in FastF1's code. But I'll see what I can do.

**Comment by bpitarch** [comment]
I confirm that it works using python 3.9.9. Maybe it should be noted somewhere in the docs that live timing doesn't work with python 3.10

**Comment by theOehrly** [comment]
Yes, I will add a note. I didn't actually know about this yet. That's why it isn't noted anywhere.
