### ISSUE TITLE
[BUG] <Loading Bahrain GP 2021 Race Session Data doesn't work>

### ISSUE THREAD

**Issue by Aleksandar-Mladenoski** [theOehrly/Fast-F1#649]
### Describe the issue:

When trying the load the 2021 Bahrain GP Race session, I get an error for "DriverNumber". This session hasn't been cancelled, so it for sure should load.

### Reproduce the code example:

```python
event = fastf1.get_event(2022, "Bahrain Grand Prix")
race = event.get_session("Race")
race.load()

This code does not work.
```

### Error message:

```shell
Traceback (most recent call last):
  File "G:\F1ML\F1ML\test.py", line 6, in <module>
    race.load()
  File "C:\Users\Alex\.conda\envs\Formel1-CondaENV\Lib\site-packages\fastf1\core.py", line 1415, in load
    self._load_drivers_results(livedata=livedata)
  File "C:\Users\Alex\.conda\envs\Formel1-CondaENV\Lib\site-packages\fastf1\core.py", line 2146, in _load_drivers_results
    driver_info_f1 = self._drivers_from_f1_api(livedata=livedata)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\.conda\envs\Formel1-CondaENV\Lib\site-packages\fastf1\core.py", line 2230, in _drivers_from_f1_api
    return pd.DataFrame(driver_info, index=driver_info['DriverNumber'])
                                           ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'DriverNumber'
```

**Comment by Casper-Guo** [comment]
What version on you on? Try updating to the newest version and see if that solves it.

**Comment by Aleksandar-Mladenoski** [comment]
Yeah it was 3.3.1, now I updated it and it's 3.4.1. I apologise for the confusion. I updated it in normal pip and not with conda, so I thought it was up to date but nope.
